name: Enviar recordatorio de clases

on:
  schedule:
    - cron: '0 21 * * *'  # Ejecuta todos los días a las 10:00 p.m. UTC
  workflow_dispatch:      # Permite ejecución manual

jobs:
  enviar-recordatorio:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar recordatorio
        run: python main.py

